package pt.ipleiria.estg.es1.financaspessoais.vista;

import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pt.ipleiria.estg.es1.financaspessoais.modelo.Conta;
import pt.ipleiria.estg.es1.financaspessoais.modelo.GestaoFinancas;
import pt.ipleiria.estg.es1.financaspessoais.modelo.Movimento;
import pt.ipleiria.estg.es1.financaspessoais.modelo.TipoMovimento;

public class MovimentosConta extends javax.swing.JDialog {

    private Conta conta;
    
    /**
     * Creates new form MovimentosConta
     */
    public MovimentosConta(java.awt.Frame parent, Conta conta) {
        super(parent, true);
        this.conta=conta;
        initComponents();
        
        actualizarDadosConta();
        actualizarMovimentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMovimentos = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome da Conta:");

        jLabel2.setText("Tipo de Conta:");

        lstMovimentos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstMovimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMovimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstMovimentos);

        jLabel3.setText("Saldo actual:");

        btnOk.setText("Voltar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        jLabel4.setText("Movimentos:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNome.setText("jLabel5");

        lblTipo.setText("jLabel6");

        lblSaldo.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTipo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSaldo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNome)))
                                .addGap(0, 370, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        Movimento m=new Movimento("", 0, TipoMovimento.DEBITO);
        DadosMovimento dialog=new DadosMovimento((Frame)getParent(), m);
        dialog.setVisible(true);
        if (dialog.isAceite()) {
            conta.adicionarMovimento(m);
            actualizarMovimentos();
            actualizarDadosConta();
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Movimento m=(Movimento)lstMovimentos.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "Tem a certeza?")==JOptionPane.YES_OPTION) {
            conta.removerMovimento(m);
            actualizarMovimentos();
            actualizarDadosConta();
        
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void lstMovimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMovimentosMouseClicked
        if (evt.getClickCount()>=2) {
            
            Movimento m=(Movimento)lstMovimentos.getSelectedValue();
            Movimento antigo=null;
            try {
                antigo = (Movimento)m.clone();
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(MovimentosConta.class.getName()).log(Level.SEVERE, null, ex);
            }
            DadosMovimento dialog=new DadosMovimento((Frame)getParent(), m);
            dialog.setVisible(true);
            if (dialog.isAceite()) {
                conta.actualizarSaldo(antigo, m);
                actualizarMovimentos();
                actualizarDadosConta();
            }
        }
    }//GEN-LAST:event_lstMovimentosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JList lstMovimentos;
    // End of variables declaration//GEN-END:variables

    private void actualizarDadosConta() {
        lblNome.setText(conta.getNome());
        lblTipo.setText(conta.getTipo().toString());
        lblSaldo.setText(Double.toString(conta.getSaldo()));
    }
    
    private void actualizarMovimentos() {
        DefaultListModel modelo=new DefaultListModel();
        for (Movimento m: conta.getMovimentos())
            modelo.addElement(m);
        lstMovimentos.setModel(modelo);
    }
}
